use swgresource;
ALTER TABLE tGalaxy ADD COLUMN galaxyNGE SMALLINT DEFAULT 0;
ALTER TABLE tGalaxy ADD COLUMN submittedBy VARCHAR(31);
ALTER TABLE tGalaxy ADD COLUMN website VARCHAR(1023);
UPDATE tGalaxy SET galaxyNGE=1 WHERE galaxyID IN (48,74);
UPDATE tProfession SET galaxy=1337 WHERE profID=18;
UPDATE tProfession SET galaxy=-1 WHERE profID IN (28,29,30,31);
UPDATE tSchematic SET galaxy=1337 WHERE galaxy=0 AND (skillGroup LIKE '%Jedi%' OR skillGroup LIKE '%Saber%');
CREATE TABLE tGalaxyUser (galaxyID INT, userID VARCHAR(31), roleType CHAR(1), INDEX IX_galaxy_user_galaxy (galaxyID), INDEX IX_galaxy_user_user (userID));
INSERT INTO tGalaxyUser (SELECT galaxyID, 'ioscode', 'a' FROM tGalaxy);
UPDATE tPlanet SET planetName='Yavin 4' WHERE planetID=10;
UPDATE tResourceType SET resourceTypeName='Hothian Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_hoth';
UPDATE tResourceType SET resourceTypeName='Hothian Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_hoth';
UPDATE tResourceType SET resourceTypeName='Mustafarian Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_mustafar';
UPDATE tResourceType SET resourceTypeName='Mustafarian Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_mustafar';
UPDATE tResourceType SET resourceTypeName='Taanab Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_taanab';
UPDATE tResourceType SET resourceTypeName='Taanab Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_taanab';
UPDATE tResourceType SET resourceTypeName='Kaasian Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_kaas';
UPDATE tResourceType SET resourceTypeName='Kaasian Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_kaas';
UPDATE tResourceType SET resourceTypeName='Mandalore Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_mandalore';
UPDATE tResourceType SET resourceTypeName='Mandalore Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_mandalore';
UPDATE tResourceType SET resourceTypeName='Kashyyyk Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_kashyyyk';
UPDATE tResourceType SET resourceTypeName='Kashyyyk Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_kashyyyk';
UPDATE tResourceType SET resourceTypeName='Lothal Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_lothal';
UPDATE tResourceType SET resourceTypeName='Lothal Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_lothal';
UPDATE tResourceType SET resourceTypeName='Jakkuan Liquid Petro Fuel' WHERE resourceType='petrochem_fuel_liquid_jakku';
UPDATE tResourceType SET resourceTypeName='Jakkuan Solid Petro Fuel' WHERE resourceType='petrochem_fuel_solid_jakku';